name: attribution
dependencies:
  - Flask=0.10.1
  - PIL=1.1.7
  - pandas
  - numpy
  - pymysql
  - flask-wtf
  - gunicorn
  - pip:
    - pyotp
    - qrcode
    - plotly
    - xhtml2pdf
    - Flask-Cache
    - Flask-Script
    - Flask-SQLAlchemy
    - Flask-Migrate
    - Flask-Mail
    - Flask-Login
    - Flask-Bootstrap
    - Flask-Moment
