#!/bin/bash
#
# chkconfig: 2345 90 12
# description: analytics python server
#
# Get function from functions library
. /etc/init.d/functions
# Start the service
RETVAL=0
prog="analyticsweb"
LOCKFILE=/var/lock/subsys/$prog
APP_HOME=/home/backoffice/$prog
start() {
	echo -n $"Staring ${prog}: "
	cd ${APP_HOME}
	su backoffice -c "PATH=/home/backoffice/anaconda2/envs/attribution/bin:$PATH && \
			export MAIL_USERNAME=auto@rockhampton-mgt.com && export MAIL_PASSWORD=ROCK#E123 && \
			export MAIL_SENDER=auto@rockhampton-mgt.com && \
			/home/backoffice/anaconda2/envs/attribution/bin/gunicorn --workers 3 --pid ${APP_HOME}/pid --bind unix:analyticsweb.sock -m 007 manage:app &" 
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch $LOCKFILE
	success $"Analytics server statup"
	echo
	return $RETVAL
}
# Restart the service
stop() {
	echo -n $"Stoping $prog: "
	killproc -p ${APP_HOME}/pid $proc
	RETVAL=$?
	### delete pid file
	[ $RETVAL -eq 0 ] && rm -f $LOCKFILE
	echo
	return $RETVAL
}

### main logic ###
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status -p ${APP_HOME}/pid $prog
	;;	
  restart|reload|condrestart)
	stop
	start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac
exit 0
